### ISSUE TITLE
Config ke Dashboard

### ISSUE THREAD

**Issue by alfianaji24** [Rafie93/rekam-medis#1]
Untuk session ke dashboard error?

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'deleted_at' in 'where clause' (SQL: select count(*) as aggregate from `pasien` where `deleted_at` is null) \rekam-medis-master\resources\views\dashboard\registrasi.blade.php)
http://127.0.0.1:8000/dashboard

**Comment by Rafie93** [comment]
column deleted_at di tabel pasien blm dtambahkan
